LISTE1
	ORG LISTE1
	DAT $41,$42,$43,$44,$45,$46,$47,$48
LISTE2
	ORG LISTE2
	DAT $45,$46,$4C,$54,$56

START	LDA SK,$0000 
		LDA CD,$000D 
		LDA A,9	  

LOOP1	LDA B,<SK+0> 
		LDA C,5  	
		LDA YG,$0008
		INC SK
		DEC A
		BEQ END
		JMP LOOP2
	
LOOP2	CMP B,<YG+0>
		BEQ LOOP1
		INC YG
		DEC C
		BEQ LOOP3
		BRA LOOP2

LOOP3 	STA B,<CD>
		INC CD
		BRA LOOP1
				
END INT


		